import Head from "next/head";
import Link from "next/link";
import { icons } from "../styles/globalStyles";
import {
  NavbarContent,
  NavbarStyled
} from "../components/Navbar/Navbar.styles";
import Navbar from "../components/Navbar/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HTML верстальщик</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main></main>

      <footer></footer>
    </div>
  );
}
